web: bundle exec unicorn_rails -c /var/www/apps/landing/current/config/unicorn.rb -E production
job1: bundle exec rake resque:work RAILS_ENV=production PIDFILE=/var/www/apps/landing/run/resque1.pid QUEUES=*
job2: bundle exec rake resque:work RAILS_ENV=production PIDFILE=/var/www/apps/landing/run/resque2.pid QUEUES=*
